// Fullstack/SvelteKit/src/routes/about/+page.svelte
<svlete:head>
	<title>About Page</title>
	<meta name="description" content="A brief description of your page's content." />
</svlete:head>

<div class="flex h-full flex-1 flex-col items-center justify-center">
	<p class="mt-4 text-lg text-blue-500">
		This is the About page. Here, you'd find information about our company/project.
	</p>
</div>

// Frontend/React/src/pages/About.jsx
import { useState, useEffect } from "react";

function About() {
    const [message, setMessage] = useState("Welcome to the About page!");

    useEffect(() => {
        console.log("About component mounted!");

        return () => {
            console.log("About component unmounted!");
        };
    }, []);

    useEffect(() => {
        setMessage(`About page loaded!`);
    }, []);

    return (
        <div className="flex flex-col items-center justify-center min-h-screen text-white">
            <h1 className="text-3xl font-bold text-blue-500">{message}</h1>

            <p className="mt-4 text-lg text-blue-500">This is the About page. Here, you'd find information about our company/project.</p>
        </div>
    );
}

export default About;
