// Frontend/React/src/components/Navbar.jsx
import { Link } from "react-router-dom";

function Navbar() {
    return (
        <nav className="bg-gray-900 text-white p-4">
            <div className="container mx-auto flex justify-between items-center">
                <Link to="/" className="text-2xl font-bold">
                    ExampleSite
                </Link>
                <div className="space-x-4">
                    <Link to="/" className="hover:text-gray-400">
                        Home
                    </Link>
                    <Link to="/about" className="hover:text-gray-400">
                        About
                    </Link>
                </div>
            </div>
        </nav>
    );
}

export default Navbar;

// Fullstack/SvelteKit/src/lib/components/Navbar.svelte
<script>
	let links = [
		{ href: '/', label: 'Home' },
		{ href: '/about', label: 'About' }
	];
</script>

<nav class="bg-gray-900 p-4 text-white">
	<div class="container mx-auto flex items-center justify-between">
		<a href="/" class="text-2xl font-bold">ExampleSite</a>
		<ul class="flex space-x-4">
			{#each links as link}
				<li>
					<a href={link.href} class="transition duration-300 hover:text-gray-400">
						{link.label}
					</a>
				</li>
			{/each}
		</ul>
	</div>
</nav>
